services:
  # конфигурация по умолчанию в *этом* файле
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  # Обработка данных в самом конце исполнения страницы
  Prokl\WebProfilierBundle\Events\DataCollectingEventHandler:
    class: Prokl\WebProfilierBundle\Events\DataCollectingEventHandler
    arguments:
      - '@profiler'
      - '@transformers.bag'
      - '@Prokl\WebProfilierBundle\Utils\ProfilerGuard'
      - '@Prokl\WebProfilierBundle\Contract\DataFileHandlerInterface'
    tags:
      - { name: bitrix.events.init, module: main, event: OnAfterEpilog, method: handle, sort: 1 }

  Prokl\WebProfilierBundle\Events\BitrixOnBeforePrologHandler:
    class: Prokl\WebProfilierBundle\Events\BitrixOnBeforePrologHandler
    arguments:
      - '@profiler'
    tags:
      - { name: bitrix.events.init, module: main, event: OnBeforeProlog, method: handle, sort: 1 }

  # Кастомное событие, чтобы проставить заголовки
  Prokl\WebProfilierBundle\Events\BitrixAfterHandleRequestListener:
    class: Prokl\WebProfilierBundle\Events\BitrixAfterHandleRequestListener
    arguments: ['@Prokl\WebProfilierBundle\Utils\ProfilerGuard', '%web_profilier.ignoring_url%']
    tags:
      - { name: kernel.event_listener, event: kernel.after_handle_request, method: handle, priority: 1 }

  # Очистка json файла профайлера.
  profilier_data_eraser:
    class: Prokl\WebProfilierBundle\EraserData
    arguments:
      - '@Prokl\WebProfilierBundle\Contract\UniqualizatorProfileDataInterface'
      - '%web_profilier.profiler_cache_path%'

  #############
  # Controllers
  #############

  Prokl\WebProfilierBundle\Controller\EraserDataController:
    class: Prokl\WebProfilierBundle\Controller\EraserDataController
    arguments: ['@profilier_data_eraser']

  ########
  # Utils
  ########

  Prokl\WebProfilierBundle\Utils\ProfilerGuard:
    class: Prokl\WebProfilierBundle\Utils\ProfilerGuard
    arguments:
      - '%kernel.environment%'

  data_file_storage_uniqualizator:
    class: Prokl\WebProfilierBundle\Bitrix\BitrixUniqualizatorProfileData

  Prokl\WebProfilierBundle\Contract\UniqualizatorProfileDataInterface: '@data_file_storage_uniqualizator'
