_profiler:
  path: /_profiler/
  controller: 'Prokl\WebProfilierBundle\Controller\ProfilerAdminController::action'

_profiler_clear:
  path: /_profiler/clear/
  controller: 'Prokl\WebProfilierBundle\Controller\EraserDataController::action'