_profiler:
  path: /_profiler/
  controller: 'Prokl\WebProfilierBundle\Controller\ProfilerAdminController::action'

_profiler_token:
  path: /_profiler/token/
  controller: 'Prokl\WebProfilierBundle\Controller\ProfilerController::action'

_profiler_token_render:
  path: /_profiler/token/render/
  controller: 'Prokl\WebProfilierBundle\Controller\ProfilerAdminController::token'

_profiler_clear:
  path: /_profiler/clear/
  controller: 'Prokl\WebProfilierBundle\Controller\EraserDataController::action'