parameters:
  # Где лежит кэш.
  json_profiler: '%kernel.cache_dir%/profiler.json'
  # Шаблон страницы админа.
  admin_profiler_page_template: './profiler/layout.html.twig'

services:
  # конфигурация по умолчанию в *этом* файле
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Symfony\Component\VarDumper\Dumper\HtmlDumper: ~

  #############
  # Controllers
  #############

  Prokl\WebProfilierBundle\Controller\ProfilerAdminController:
    class: Prokl\WebProfilierBundle\Controller\ProfilerAdminController
    arguments:
      - '@profilier.twig'
      - '@Prokl\WebProfilierBundle\Contract\DataFileHandlerInterface'
      - '%admin_profiler_page_template%'
      - '%json_profiler%'

  ########
  # Utils
  ########

  ordinary_data_file_storage_uniqualizator:
    class: Prokl\WebProfilierBundle\Utils\OrdinaryUniqualizatorProfileData

  profilier_data_file_handler:
    class: Prokl\WebProfilierBundle\Utils\DataFileHandler
    arguments:
      - '@Prokl\WebProfilierBundle\Contract\UniqualizatorProfileDataInterface'
      - '%json_profiler%'

  Prokl\WebProfilierBundle\Contract\DataFileHandlerInterface: '@profilier_data_file_handler'