services:
  # конфигурация по умолчанию в *этом* файле
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Symfony\Component\VarDumper\Dumper\HtmlDumper: ~

  #############
  # Controllers
  #############

  Prokl\WebProfilierBundle\Controller\ProfilerAdminController:
    class: Prokl\WebProfilierBundle\Controller\ProfilerAdminController
    arguments:
      - '@profilier.twig'
      - '@Prokl\WebProfilierBundle\Contract\DataFileHandlerInterface'
      - '@bitrix.user'
      - '%web_profilier.admin_profiler_page_template%'
      - '%web_profilier.profiler_cache_path%'

  ########
  # Utils
  ########

  bitrix.user:
    public: false
    class: CUser

  ordinary_data_file_storage_uniqualizator:
    class: Prokl\WebProfilierBundle\Utils\OrdinaryUniqualizatorProfileData

  profilier_data_file_handler:
    class: Prokl\WebProfilierBundle\Utils\DataFileHandler
    arguments:
      - '@Prokl\WebProfilierBundle\Contract\UniqualizatorProfileDataInterface'
      - '%web_profilier.profiler_cache_path%'

  Prokl\WebProfilierBundle\Contract\DataFileHandlerInterface: '@profilier_data_file_handler'